### PR TITLE
gnsz6753 66 n

### PR DESCRIPTION
**Pull request by algphello**
Add device tree to build TWRP for Condor Allure A8 for Android 7.0 with version kernel 3.18.35

### CODE REVIEW

**Comment by berkantkz** [comment]
In what purpose you made these changes? Was there any issue with the original one?

**Comment by algphello** [comment]
This is for build twrp for the device to support kernel version 3.18.35
because the old tree is for 3.18.19 only and not work in 3.18.35
I test it in my device and all thing works

Le dim. 20 mai 2018 à 01:33, Berkant Korkmaz <notifications@github.com> a
écrit :

**Comment by androidlover5842** [comment]
you can't rename device codename else it will break Travis corn jobs, if you have issues with codename then add ota asserts in boardconfig and update kernel .

**Comment by algphello** [comment]
In the kernel 3.18.35 the device comme with gnsz6753_66_n so not me make
the change

Le dim. 20 mai 2018 à 08:09, androidlover5842 <notifications@github.com> a
écrit :

**Pull request closed without merging**
